### ISSUE TITLE
error: react-native run-ios

### ISSUE THREAD

**Issue by kaixinfu** [GeekyAnts/reazy#2]
1.reazy init MyAwesomeApp [mobile]
2.cd MyAwesomeApp
3.react-native run-ios
4.Command `run-ios` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

**Comment by sanketsahu** [comment]
@liukaixin01 This project isn't being maintained anymore. Thanks for your interest though.

You might like to check ReactNativeSeed.com or Ignite by InfiniteRed.
